eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

resilience4j:
    circuitbreaker:
        instances:
            myCircuitBreaker:
                minimum-number-of-calls: 3
                sliding-window-size: 6
server:
    port: ${PORT:0}
spring:
    application:
        name: hr-payroll
    output:
        ansi:
            enabled: ALWAYS
    kafka:
        producer:
          bootstrap-servers:
            - localhost:9092
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
    pattern:
        level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
    endpoints:
        web:
            exposure:
                include: refresh, health, info, prometheus
    endpoint:
        refresh:
            enabled: true
    zipkin:
        tracing:
            endpoint: http://localhost:9411/api/v2/spans
    tracing:
        enabled: true
        sampling:
            probability: 1.0


