eureka:
    client:
        fetch-register: false
        register-with-eureka: false
server:
    port: 8761
spring:
    application:
        name: hr-eureka-server
    output:
        ansi:
            enabled: ALWAYS