global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    scrape_timeout: 15s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'eureka-discovery'
    scrape_interval: 15s
    scrape_timeout: 15s
    params:
      module: [ http_2xx ]
    metrics_path: /actuator/prometheus
    eureka_sd_configs:
      - server: 'http://192.168.18.139:8761/eureka'
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [ __meta_eureka_app_name ]
        target_label: application
      - source_labels: [ __meta_eureka_app_instance_metadata_metrics_path ]
        regex: (.+)
        target_label: __metrics_path__
        replacement: '${1}'
      - source_labels: [ __meta_eureka_instance_host_name, __meta_eureka_instance_port ]
        separator: ':'
        regex: (.+):(.+)
        target_label: __address__
        replacement: '${1}:${2}'
      - source_labels: [ __meta_eureka_instance_app ]
        target_label: job

  - job_name: 'blackbox-via-service-discovery'
    params:
      module: [ http_2xx ]
    scrape_interval: 15s
    scrape_timeout: 15s
    metrics_path: /actuator/prometheus
    eureka_sd_configs:
      - server: 'http://192.168.18.139:8761/eureka'
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [ __meta_eureka_app_name ]
        target_label: application
      - source_labels: [ __meta_eureka_app_instance_healthcheck_url ]
        target_label: __param_target
      - source_labels: [ __meta_eureka_instance_host_name, __meta_eureka_instance_port ]
        separator: ':'
        regex: (.+):(.+)
        target_label: instance
        replacement: '${1}:${2}'
      - target_label: __address__
        replacement: blackbox-exporter:9115


