eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
server:
    port: ${PORT:0}
spring:
    application:
        name: hr-user
    profiles:
      active:
        - dev
    output:
        ansi:
            enabled: ALWAYS
logging:
    pattern:
        level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
    endpoints:
        web:
            exposure:
                include: refresh, health, info
    endpoint:
        refresh:
            enabled: true
    zipkin:
        tracing:
            endpoint: http://localhost:9411/api/v2/spans
    tracing:
        enabled: true
        sampling:
            probability: 1.0

